# Generated by Django 4.1.4 on 2023-02-10 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pasciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('dataNascimento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataConsulta', models.DateField()),
                ('horarioConsulta', models.TimeField()),
                ('hospital', models.CharField(max_length=50)),
                ('acompanhante', models.BooleanField()),
                ('observacao', models.CharField(max_length=255)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.pasciente')),
            ],
        ),
    ]
