# Generated by Django 4.1.4 on 2023-02-10 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pasciente',
            new_name='Paciente',
        ),
    ]
